server:
  port: 8090

hello:
  sha: aaaaaa
  world: Hello World! from Delivery-Relay-Service ${hello.sha}.from Here

spring:
  profiles:
    active: production
  mongodb:
    embedded:
      version: 3.5.5

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,env,configprops
