server:
  port: 8090

spring:
  data:
    mongodb:
      database: inbobwetrust
      uri: localhost:27107
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0
  application:
    name: delivery-relay-service

