wiremock:
  server:
    httpsPort: -1
  reset-mappings-after-each-test: true

server:
  port: 8888

restClient:
  proxy:
    shopUrl: ${restClient.proxy.baseUrl}/relay/v1/shop
    agencyUrl: ${restClient.proxy.baseUrl}/relay/v1/agency


  metrics:
    export:
      cloudwatch:
        namespace: m3trics2
        batchSize: 20
