wiremock:
  server:
    httpsPort: -1
  reset-mappings-after-each-test: true

server:
  port: 8888

restClient:
  proxy:
    baseUrl: http://localhost:8090
    shopUrl: ${restClient.proxy.baseUrl}/relay/v1/shop
    agencyUrl: ${restClient.proxy.baseUrl}/relay/v1/agency

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,env,configprops,threaddump

spring:
  data:
    mongodb:
      database: inbobwetrust
      uri: mongodb://localhost:27017
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 0.05
  application:
    name: delivery-info-service