wiremock:
  server:
    httpsPort: -1
  reset-mappings-after-each-test: true

server:
  port: 8888

spring:
  profiles:
    active: production
  mongodb:
    embedded:
      version: 3.5.5

docker:
  image:
    version: -1

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,env,configprops


hello:
  world: Hello World! - delivery-info-service v.${docker.image.version}

