server:
  port: 8888

restClient:
  proxy:
    baseUrl: http://localhost:8090
    shopUrl: ${restClient.proxy.baseUrl}/relay/v1/shop
    agencyUrl: ${restClient.proxy.baseUrl}/relay/v1/agency

spring:
  data:
    mongodb:
      database: inbobwetrust
      uri: mongodb://localhost:27017
