package com.inbobwetrust.entitiy;

public enum OrderStatus {
    PAYMENT_READY,
    PAYMENT_FINISH,
    RIDER_MATCH_READY,
    RIDER_MATCH_FINISH,
    PICKUP_READY,
    DELIVERY_GO,
    DELIVERY_FINISH,
    PAYMENT_CANCEL,
    RIDER_MATCH_CANCEL,
    DELIVERY_CANCEL
}
