spring:
  sql:
    init:
      mode: always
  h2:
    console.enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:order_server;MODE=MySQL;
    username: SA
    password:
    initialization-mode: always
    schema: classpath:schema.sql
    data: classpath:data-test-h2.sql
