server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/inbobwetrust?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1qaz@WSX

mybatis:
  type-aliases-package: com.inbobwetrust.model
  mapper-locations:
    - classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

