# Example workflow
name: google-java-format

on:
  push:
    branches:
      - '12345'
jobs:

  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # v2 minimum required
      - uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--replace"
          commitMessage: "Format : Google Java Format"
