# Example workflow
name: Format

on: [ push ]

jobs:

  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--replace"
          commitMessage: "Format : Google Java Format"
